# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: :title
# https://help.github.com/articles/migrating-your-pages-site-from-maruku
markdown: kramdown

highlighter: rouge
paginate: 10 # pagination based on number of posts
paginate_path: "page/:num"

# These paths are to the main pages Jekyll-Bootstrap ships with.
# Some JB helpers refer to these paths; change them here if needed.
categories_path : categories.html
tags_path : tags.html

BASE_PATH : "https://kzhinan.github.io"

title : KZhiNan

author:
  name: KzhiNan
  role: Jekyll Theme
  email: tkdqja7189@gmail.com
  github: KzhiNan
  twitter: ""
  facebook: ""
  googleplus: ""
#  bio: "授人以鱼，不如授人以渔"
  logo: /assets/media/log.jpg
  # uno-dbyll: https://raw.githubusercontent.com/meliodus/uno-dbyll/gh-pages/uno-dbyll.png
# raw.githubusercontent.com/${user}/${repo}/${branch}/${path}
